server:
  port: ${PORT:0}


spring:
        
  rabbitmq:
    host: ${RABBITMQ_SERVER_IP:192.168.15.168}
    port: 5672
    virtual-host: teste-duda
    username: ${RABBITMQ_SERVER_USER:duda}
    password: ${RABBITMQ_SERVER_PASS:duda123}
    listener: 
      simple:
        concurrency: ${RABBITMQ_NUMBER_CONSUMERS:1}
        prefetch: ${RABBITMQ_NUMBER_MESSAGES:1}
        
        
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: 154154marcia@gmail.com
    password: 154154duda
    properties.mail.smtp:
        auth: true
        starttls.enable: true

queue:
  name_queue_duda: teste
